services:
  database:
    image: "docker.io/postgres:latest"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/

  pgadmin:
    image: "docker.io/dpage/pgadmin4:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - 3002:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

volumes:
  pg-data:
  pgadmin-data:
